/*
 * This file is generated by jOOQ.
 */
package com.example.demo.system.repository.jooq.tables;


import com.example.demo.system.repository.jooq.DefaultSchema;
import com.example.demo.system.repository.jooq.Keys;
import com.example.demo.system.repository.jooq.tables.records.SysPermissionRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SysPermission extends TableImpl<SysPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sys_permission</code>
     */
    public static final SysPermission SYS_PERMISSION = new SysPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysPermissionRecord> getRecordType() {
        return SysPermissionRecord.class;
    }

    /**
     * The column <code>sys_permission.id</code>.
     */
    public final TableField<SysPermissionRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>sys_permission.user_id</code>. 用户 ID
     */
    public final TableField<SysPermissionRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(64).nullable(false), this, "用户 ID");

    /**
     * The column <code>sys_permission.role_id</code>. 角色 ID
     */
    public final TableField<SysPermissionRecord, String> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.VARCHAR(64).nullable(false), this, "角色 ID");

    /**
     * The column <code>sys_permission.create_by</code>. 创建人
     */
    public final TableField<SysPermissionRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "创建人");

    /**
     * The column <code>sys_permission.create_time</code>. 创建时间
     */
    public final TableField<SysPermissionRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>sys_permission.update_by</code>. 更新人
     */
    public final TableField<SysPermissionRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "更新人");

    /**
     * The column <code>sys_permission.update_time</code>. 更新时间
     */
    public final TableField<SysPermissionRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "更新时间");

    private SysPermission(Name alias, Table<SysPermissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SysPermission(Name alias, Table<SysPermissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("用户角色表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sys_permission</code> table reference
     */
    public SysPermission(String alias) {
        this(DSL.name(alias), SYS_PERMISSION);
    }

    /**
     * Create an aliased <code>sys_permission</code> table reference
     */
    public SysPermission(Name alias) {
        this(alias, SYS_PERMISSION);
    }

    /**
     * Create a <code>sys_permission</code> table reference
     */
    public SysPermission() {
        this(DSL.name("sys_permission"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<SysPermissionRecord> getPrimaryKey() {
        return Keys.KEY_SYS_PERMISSION_PRIMARY;
    }

    @Override
    public SysPermission as(String alias) {
        return new SysPermission(DSL.name(alias), this);
    }

    @Override
    public SysPermission as(Name alias) {
        return new SysPermission(alias, this);
    }

    @Override
    public SysPermission as(Table<?> alias) {
        return new SysPermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysPermission rename(String name) {
        return new SysPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysPermission rename(Name name) {
        return new SysPermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysPermission rename(Table<?> name) {
        return new SysPermission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysPermission where(Condition condition) {
        return new SysPermission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysPermission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysPermission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysPermission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysPermission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysPermission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysPermission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysPermission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysPermission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysPermission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
