/*
 * This file is generated by jOOQ.
 */
package com.example.demo.system.repository.jooq;


import com.example.demo.system.repository.jooq.tables.SysPermission;
import com.example.demo.system.repository.jooq.tables.SysRole;
import com.example.demo.system.repository.jooq.tables.SysUser;
import com.example.demo.system.repository.jooq.tables.SysUserRole;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 用户角色表
     */
    public static final SysPermission SYS_PERMISSION = SysPermission.SYS_PERMISSION;

    /**
     * 角色表
     */
    public static final SysRole SYS_ROLE = SysRole.SYS_ROLE;

    /**
     * 用户表
     */
    public static final SysUser SYS_USER = SysUser.SYS_USER;

    /**
     * 用户角色表
     */
    public static final SysUserRole SYS_USER_ROLE = SysUserRole.SYS_USER_ROLE;
}
