server:
  port: 8080 # 明确指定网关端口为 8080
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
# JWT 配置（需与 api-gateway 的配置完全一致！）
application:
  security:
    jwt:
      secret-key: Y2F0Y2hlciUyMHdvcmtpbmd8c3ByaW5nJTIwY2xvdWQlMjBpcyUyMHBhcGVyIQ==  # Base64 编码的密钥（自己生成）
