/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables;


import com.example.demo.resources.repository.jooq.DefaultSchema;
import com.example.demo.resources.repository.jooq.Keys;
import com.example.demo.resources.repository.jooq.tables.records.ResCollegeRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 学院表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResCollege extends TableImpl<ResCollegeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>res_college</code>
     */
    public static final ResCollege RES_COLLEGE = new ResCollege();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResCollegeRecord> getRecordType() {
        return ResCollegeRecord.class;
    }

    /**
     * The column <code>res_college.id</code>. 学院 ID（主键）
     */
    public final TableField<ResCollegeRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "学院 ID（主键）");

    /**
     * The column <code>res_college.college_code</code>.
     */
    public final TableField<ResCollegeRecord, String> COLLEGE_CODE = createField(DSL.name("college_code"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_college.campus_id</code>.
     */
    public final TableField<ResCollegeRecord, String> CAMPUS_ID = createField(DSL.name("campus_id"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_college.college_name</code>.
     */
    public final TableField<ResCollegeRecord, String> COLLEGE_NAME = createField(DSL.name("college_name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_college.college_abbr</code>.
     */
    public final TableField<ResCollegeRecord, String> COLLEGE_ABBR = createField(DSL.name("college_abbr"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_college.english_name</code>.
     */
    public final TableField<ResCollegeRecord, String> ENGLISH_NAME = createField(DSL.name("english_name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_college.dean</code>.
     */
    public final TableField<ResCollegeRecord, String> DEAN = createField(DSL.name("dean"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_college.landline</code>.
     */
    public final TableField<ResCollegeRecord, String> LANDLINE = createField(DSL.name("landline"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_college.phone</code>.
     */
    public final TableField<ResCollegeRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_college.email</code>.
     */
    public final TableField<ResCollegeRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_college.intro</code>.
     */
    public final TableField<ResCollegeRecord, String> INTRO = createField(DSL.name("intro"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_college.create_by</code>. 创建人
     */
    public final TableField<ResCollegeRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "创建人");

    /**
     * The column <code>res_college.create_time</code>. 创建时间
     */
    public final TableField<ResCollegeRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>res_college.update_by</code>. 更新人
     */
    public final TableField<ResCollegeRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "更新人");

    /**
     * The column <code>res_college.update_time</code>. 更新时间
     */
    public final TableField<ResCollegeRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>res_college.campus_name</code>.
     */
    public final TableField<ResCollegeRecord, String> CAMPUS_NAME = createField(DSL.name("campus_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>res_college.chinese_abbr</code>.
     */
    public final TableField<ResCollegeRecord, String> CHINESE_ABBR = createField(DSL.name("chinese_abbr"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private ResCollege(Name alias, Table<ResCollegeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ResCollege(Name alias, Table<ResCollegeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("学院表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>res_college</code> table reference
     */
    public ResCollege(String alias) {
        this(DSL.name(alias), RES_COLLEGE);
    }

    /**
     * Create an aliased <code>res_college</code> table reference
     */
    public ResCollege(Name alias) {
        this(alias, RES_COLLEGE);
    }

    /**
     * Create a <code>res_college</code> table reference
     */
    public ResCollege() {
        this(DSL.name("res_college"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ResCollegeRecord> getPrimaryKey() {
        return Keys.KEY_RES_COLLEGE_PRIMARY;
    }

    @Override
    public ResCollege as(String alias) {
        return new ResCollege(DSL.name(alias), this);
    }

    @Override
    public ResCollege as(Name alias) {
        return new ResCollege(alias, this);
    }

    @Override
    public ResCollege as(Table<?> alias) {
        return new ResCollege(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResCollege rename(String name) {
        return new ResCollege(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResCollege rename(Name name) {
        return new ResCollege(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResCollege rename(Table<?> name) {
        return new ResCollege(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCollege where(Condition condition) {
        return new ResCollege(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCollege where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCollege where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCollege where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCollege where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCollege where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCollege where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCollege where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCollege whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCollege whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
