/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables;


import com.example.demo.resources.repository.jooq.DefaultSchema;
import com.example.demo.resources.repository.jooq.Indexes;
import com.example.demo.resources.repository.jooq.Keys;
import com.example.demo.resources.repository.jooq.tables.records.ResCourseRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 课程表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResCourse extends TableImpl<ResCourseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>res_course</code>
     */
    public static final ResCourse RES_COURSE = new ResCourse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResCourseRecord> getRecordType() {
        return ResCourseRecord.class;
    }

    /**
     * The column <code>res_course.id</code>.
     */
    public final TableField<ResCourseRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>res_course.course_code</code>.
     */
    public final TableField<ResCourseRecord, String> COURSE_CODE = createField(DSL.name("course_code"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_course.course_name</code>.
     */
    public final TableField<ResCourseRecord, String> COURSE_NAME = createField(DSL.name("course_name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_course.english_name</code>.
     */
    public final TableField<ResCourseRecord, String> ENGLISH_NAME = createField(DSL.name("english_name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_course.department_id</code>.
     */
    public final TableField<ResCourseRecord, String> DEPARTMENT_ID = createField(DSL.name("department_id"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_course.major_id</code>.
     */
    public final TableField<ResCourseRecord, String> MAJOR_ID = createField(DSL.name("major_id"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_course.teacher_id</code>.
     */
    public final TableField<ResCourseRecord, String> TEACHER_ID = createField(DSL.name("teacher_id"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_course.credit</code>.
     */
    public final TableField<ResCourseRecord, Double> CREDIT = createField(DSL.name("credit"), SQLDataType.DOUBLE.defaultValue(DSL.inline("NULL", SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>res_course.total_hours</code>. 总学时（理论+实践）
     */
    public final TableField<ResCourseRecord, Integer> TOTAL_HOURS = createField(DSL.name("total_hours"), SQLDataType.INTEGER.nullable(false), this, "总学时（理论+实践）");

    /**
     * The column <code>res_course.theory_hours</code>. 理论学时
     */
    public final TableField<ResCourseRecord, Integer> THEORY_HOURS = createField(DSL.name("theory_hours"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "理论学时");

    /**
     * The column <code>res_course.practice_hours</code>. 实践学时
     */
    public final TableField<ResCourseRecord, Integer> PRACTICE_HOURS = createField(DSL.name("practice_hours"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "实践学时");

    /**
     * The column <code>res_course.course_type_code</code>.
     */
    public final TableField<ResCourseRecord, String> COURSE_TYPE_CODE = createField(DSL.name("course_type_code"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_course.teaching_mode_code</code>.
     */
    public final TableField<ResCourseRecord, String> TEACHING_MODE_CODE = createField(DSL.name("teaching_mode_code"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_course.assessment_type_code</code>.
     */
    public final TableField<ResCourseRecord, String> ASSESSMENT_TYPE_CODE = createField(DSL.name("assessment_type_code"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_course.description</code>.
     */
    public final TableField<ResCourseRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_course.create_by</code>. 创建人
     */
    public final TableField<ResCourseRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "创建人");

    /**
     * The column <code>res_course.create_time</code>. 创建时间
     */
    public final TableField<ResCourseRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>res_course.update_by</code>. 更新人
     */
    public final TableField<ResCourseRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "更新人");

    /**
     * The column <code>res_course.update_time</code>. 更新时间
     */
    public final TableField<ResCourseRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>res_course.chinese_name</code>.
     */
    public final TableField<ResCourseRecord, String> CHINESE_NAME = createField(DSL.name("chinese_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private ResCourse(Name alias, Table<ResCourseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ResCourse(Name alias, Table<ResCourseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("课程表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>res_course</code> table reference
     */
    public ResCourse(String alias) {
        this(DSL.name(alias), RES_COURSE);
    }

    /**
     * Create an aliased <code>res_course</code> table reference
     */
    public ResCourse(Name alias) {
        this(alias, RES_COURSE);
    }

    /**
     * Create a <code>res_course</code> table reference
     */
    public ResCourse() {
        this(DSL.name("res_course"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.RES_COURSE_IDX_SEMESTER_DEPARTMENT, Indexes.RES_COURSE_IDX_TEACHER_ID);
    }

    @Override
    public UniqueKey<ResCourseRecord> getPrimaryKey() {
        return Keys.KEY_RES_COURSE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ResCourseRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_RES_COURSE_UK_COURSE_CODE);
    }

    @Override
    public ResCourse as(String alias) {
        return new ResCourse(DSL.name(alias), this);
    }

    @Override
    public ResCourse as(Name alias) {
        return new ResCourse(alias, this);
    }

    @Override
    public ResCourse as(Table<?> alias) {
        return new ResCourse(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResCourse rename(String name) {
        return new ResCourse(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResCourse rename(Name name) {
        return new ResCourse(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResCourse rename(Table<?> name) {
        return new ResCourse(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCourse where(Condition condition) {
        return new ResCourse(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCourse where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCourse where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCourse where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCourse where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCourse where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCourse where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCourse where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCourse whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCourse whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
