/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables;


import com.example.demo.resources.repository.jooq.DefaultSchema;
import com.example.demo.resources.repository.jooq.Keys;
import com.example.demo.resources.repository.jooq.tables.records.ResCampusRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 校区表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResCampus extends TableImpl<ResCampusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>res_campus</code>
     */
    public static final ResCampus RES_CAMPUS = new ResCampus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResCampusRecord> getRecordType() {
        return ResCampusRecord.class;
    }

    /**
     * The column <code>res_campus.id</code>.
     */
    public final TableField<ResCampusRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>res_campus.campus_code</code>.
     */
    public final TableField<ResCampusRecord, String> CAMPUS_CODE = createField(DSL.name("campus_code"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_campus.school_id</code>.
     */
    public final TableField<ResCampusRecord, String> SCHOOL_ID = createField(DSL.name("school_id"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_campus.campus_name</code>.
     */
    public final TableField<ResCampusRecord, String> CAMPUS_NAME = createField(DSL.name("campus_name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_campus.english_name</code>.
     */
    public final TableField<ResCampusRecord, String> ENGLISH_NAME = createField(DSL.name("english_name"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_campus.address</code>.
     */
    public final TableField<ResCampusRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_campus.principal</code>.
     */
    public final TableField<ResCampusRecord, String> PRINCIPAL = createField(DSL.name("principal"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_campus.landline</code>.
     */
    public final TableField<ResCampusRecord, String> LANDLINE = createField(DSL.name("landline"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_campus.phone</code>.
     */
    public final TableField<ResCampusRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_campus.email</code>.
     */
    public final TableField<ResCampusRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_campus.intro</code>.
     */
    public final TableField<ResCampusRecord, String> INTRO = createField(DSL.name("intro"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_campus.create_by</code>. 创建人
     */
    public final TableField<ResCampusRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "创建人");

    /**
     * The column <code>res_campus.create_time</code>. 创建时间
     */
    public final TableField<ResCampusRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>res_campus.update_by</code>. 更新人
     */
    public final TableField<ResCampusRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "更新人");

    /**
     * The column <code>res_campus.update_time</code>. 更新时间
     */
    public final TableField<ResCampusRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "更新时间");

    private ResCampus(Name alias, Table<ResCampusRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ResCampus(Name alias, Table<ResCampusRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("校区表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>res_campus</code> table reference
     */
    public ResCampus(String alias) {
        this(DSL.name(alias), RES_CAMPUS);
    }

    /**
     * Create an aliased <code>res_campus</code> table reference
     */
    public ResCampus(Name alias) {
        this(alias, RES_CAMPUS);
    }

    /**
     * Create a <code>res_campus</code> table reference
     */
    public ResCampus() {
        this(DSL.name("res_campus"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ResCampusRecord> getPrimaryKey() {
        return Keys.KEY_RES_CAMPUS_PRIMARY;
    }

    @Override
    public ResCampus as(String alias) {
        return new ResCampus(DSL.name(alias), this);
    }

    @Override
    public ResCampus as(Name alias) {
        return new ResCampus(alias, this);
    }

    @Override
    public ResCampus as(Table<?> alias) {
        return new ResCampus(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResCampus rename(String name) {
        return new ResCampus(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResCampus rename(Name name) {
        return new ResCampus(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResCampus rename(Table<?> name) {
        return new ResCampus(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCampus where(Condition condition) {
        return new ResCampus(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCampus where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCampus where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCampus where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCampus where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCampus where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCampus where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResCampus where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCampus whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResCampus whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
