/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables;


import com.example.demo.resources.repository.jooq.DefaultSchema;
import com.example.demo.resources.repository.jooq.Keys;
import com.example.demo.resources.repository.jooq.tables.records.ResDepartmentRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 部门表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResDepartment extends TableImpl<ResDepartmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>res_department</code>
     */
    public static final ResDepartment RES_DEPARTMENT = new ResDepartment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResDepartmentRecord> getRecordType() {
        return ResDepartmentRecord.class;
    }

    /**
     * The column <code>res_department.id</code>.
     */
    public final TableField<ResDepartmentRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>res_department.college_id</code>. 学院 ID
     */
    public final TableField<ResDepartmentRecord, String> COLLEGE_ID = createField(DSL.name("college_id"), SQLDataType.VARCHAR(64).nullable(false), this, "学院 ID");

    /**
     * The column <code>res_department.department_code</code>. 部门编号
     */
    public final TableField<ResDepartmentRecord, String> DEPARTMENT_CODE = createField(DSL.name("department_code"), SQLDataType.VARCHAR(10).nullable(false), this, "部门编号");

    /**
     * The column <code>res_department.department_name</code>. 部门名称
     */
    public final TableField<ResDepartmentRecord, String> DEPARTMENT_NAME = createField(DSL.name("department_name"), SQLDataType.VARCHAR(100).nullable(false), this, "部门名称");

    /**
     * The column <code>res_department.create_by</code>. 创建人
     */
    public final TableField<ResDepartmentRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "创建人");

    /**
     * The column <code>res_department.create_time</code>. 创建时间
     */
    public final TableField<ResDepartmentRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>res_department.update_by</code>. 更新人
     */
    public final TableField<ResDepartmentRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "更新人");

    /**
     * The column <code>res_department.update_time</code>. 更新时间
     */
    public final TableField<ResDepartmentRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "更新时间");

    private ResDepartment(Name alias, Table<ResDepartmentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ResDepartment(Name alias, Table<ResDepartmentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("部门表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>res_department</code> table reference
     */
    public ResDepartment(String alias) {
        this(DSL.name(alias), RES_DEPARTMENT);
    }

    /**
     * Create an aliased <code>res_department</code> table reference
     */
    public ResDepartment(Name alias) {
        this(alias, RES_DEPARTMENT);
    }

    /**
     * Create a <code>res_department</code> table reference
     */
    public ResDepartment() {
        this(DSL.name("res_department"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ResDepartmentRecord> getPrimaryKey() {
        return Keys.KEY_RES_DEPARTMENT_PRIMARY;
    }

    @Override
    public ResDepartment as(String alias) {
        return new ResDepartment(DSL.name(alias), this);
    }

    @Override
    public ResDepartment as(Name alias) {
        return new ResDepartment(alias, this);
    }

    @Override
    public ResDepartment as(Table<?> alias) {
        return new ResDepartment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResDepartment rename(String name) {
        return new ResDepartment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResDepartment rename(Name name) {
        return new ResDepartment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResDepartment rename(Table<?> name) {
        return new ResDepartment(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResDepartment where(Condition condition) {
        return new ResDepartment(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResDepartment where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResDepartment where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResDepartment where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResDepartment where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResDepartment where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResDepartment where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResDepartment where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResDepartment whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResDepartment whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
