/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables;


import com.example.demo.resources.repository.jooq.DefaultSchema;
import com.example.demo.resources.repository.jooq.Keys;
import com.example.demo.resources.repository.jooq.tables.records.ResMajorRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 专业表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResMajor extends TableImpl<ResMajorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>res_major</code>
     */
    public static final ResMajor RES_MAJOR = new ResMajor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResMajorRecord> getRecordType() {
        return ResMajorRecord.class;
    }

    /**
     * The column <code>res_major.id</code>.
     */
    public final TableField<ResMajorRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>res_major.major_code</code>. 专业代码
     */
    public final TableField<ResMajorRecord, String> MAJOR_CODE = createField(DSL.name("major_code"), SQLDataType.VARCHAR(20).nullable(false), this, "专业代码");

    /**
     * The column <code>res_major.college_id</code>. 学院 ID
     */
    public final TableField<ResMajorRecord, String> COLLEGE_ID = createField(DSL.name("college_id"), SQLDataType.VARCHAR(64).nullable(false), this, "学院 ID");

    /**
     * The column <code>res_major.major_name</code>. 专业中文名称
     */
    public final TableField<ResMajorRecord, String> MAJOR_NAME = createField(DSL.name("major_name"), SQLDataType.VARCHAR(100).nullable(false), this, "专业中文名称");

    /**
     * The column <code>res_major.major_abbr</code>. 专业中文简称
     */
    public final TableField<ResMajorRecord, String> MAJOR_ABBR = createField(DSL.name("major_abbr"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "专业中文简称");

    /**
     * The column <code>res_major.english_name</code>. 专业英文名称
     */
    public final TableField<ResMajorRecord, String> ENGLISH_NAME = createField(DSL.name("english_name"), SQLDataType.VARCHAR(200).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "专业英文名称");

    /**
     * The column <code>res_major.degree</code>. 授予学位
     */
    public final TableField<ResMajorRecord, String> DEGREE = createField(DSL.name("degree"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "授予学位");

    /**
     * The column <code>res_major.years</code>. 学制年限
     */
    public final TableField<ResMajorRecord, Integer> YEARS = createField(DSL.name("years"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "学制年限");

    /**
     * The column <code>res_major.intro</code>. 简介
     */
    public final TableField<ResMajorRecord, String> INTRO = createField(DSL.name("intro"), SQLDataType.VARCHAR(1000).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "简介");

    /**
     * The column <code>res_major.create_by</code>. 创建人
     */
    public final TableField<ResMajorRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "创建人");

    /**
     * The column <code>res_major.create_time</code>. 创建时间
     */
    public final TableField<ResMajorRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>res_major.update_by</code>. 更新人
     */
    public final TableField<ResMajorRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "更新人");

    /**
     * The column <code>res_major.update_time</code>. 更新时间
     */
    public final TableField<ResMajorRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>res_major.chinese_abbr</code>.
     */
    public final TableField<ResMajorRecord, String> CHINESE_ABBR = createField(DSL.name("chinese_abbr"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>res_major.chinese_name</code>.
     */
    public final TableField<ResMajorRecord, String> CHINESE_NAME = createField(DSL.name("chinese_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private ResMajor(Name alias, Table<ResMajorRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ResMajor(Name alias, Table<ResMajorRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("专业表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>res_major</code> table reference
     */
    public ResMajor(String alias) {
        this(DSL.name(alias), RES_MAJOR);
    }

    /**
     * Create an aliased <code>res_major</code> table reference
     */
    public ResMajor(Name alias) {
        this(alias, RES_MAJOR);
    }

    /**
     * Create a <code>res_major</code> table reference
     */
    public ResMajor() {
        this(DSL.name("res_major"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ResMajorRecord> getPrimaryKey() {
        return Keys.KEY_RES_MAJOR_PRIMARY;
    }

    @Override
    public ResMajor as(String alias) {
        return new ResMajor(DSL.name(alias), this);
    }

    @Override
    public ResMajor as(Name alias) {
        return new ResMajor(alias, this);
    }

    @Override
    public ResMajor as(Table<?> alias) {
        return new ResMajor(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResMajor rename(String name) {
        return new ResMajor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResMajor rename(Name name) {
        return new ResMajor(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResMajor rename(Table<?> name) {
        return new ResMajor(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResMajor where(Condition condition) {
        return new ResMajor(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResMajor where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResMajor where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResMajor where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResMajor where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResMajor where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResMajor where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResMajor where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResMajor whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResMajor whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
