/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables;


import com.example.demo.resources.repository.jooq.DefaultSchema;
import com.example.demo.resources.repository.jooq.Keys;
import com.example.demo.resources.repository.jooq.tables.records.ResQuarterRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 学季字典表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResQuarter extends TableImpl<ResQuarterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>res_quarter</code>
     */
    public static final ResQuarter RES_QUARTER = new ResQuarter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResQuarterRecord> getRecordType() {
        return ResQuarterRecord.class;
    }

    /**
     * The column <code>res_quarter.id</code>.
     */
    public final TableField<ResQuarterRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>res_quarter.quarter_code</code>. 代码
     */
    public final TableField<ResQuarterRecord, String> QUARTER_CODE = createField(DSL.name("quarter_code"), SQLDataType.VARCHAR(20).nullable(false), this, "代码");

    /**
     * The column <code>res_quarter.quarter_name</code>. 名称
     */
    public final TableField<ResQuarterRecord, String> QUARTER_NAME = createField(DSL.name("quarter_name"), SQLDataType.VARCHAR(100).nullable(false), this, "名称");

    /**
     * The column <code>res_quarter.english_name</code>. 英文名称
     */
    public final TableField<ResQuarterRecord, String> ENGLISH_NAME = createField(DSL.name("english_name"), SQLDataType.VARCHAR(200).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "英文名称");

    /**
     * The column <code>res_quarter.create_by</code>. 创建人
     */
    public final TableField<ResQuarterRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "创建人");

    /**
     * The column <code>res_quarter.create_time</code>. 创建时间
     */
    public final TableField<ResQuarterRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>res_quarter.update_by</code>. 更新人
     */
    public final TableField<ResQuarterRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "更新人");

    /**
     * The column <code>res_quarter.update_time</code>. 更新时间
     */
    public final TableField<ResQuarterRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>res_quarter.chinese_name</code>.
     */
    public final TableField<ResQuarterRecord, String> CHINESE_NAME = createField(DSL.name("chinese_name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>res_quarter.code</code>.
     */
    public final TableField<ResQuarterRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private ResQuarter(Name alias, Table<ResQuarterRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ResQuarter(Name alias, Table<ResQuarterRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("学季字典表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>res_quarter</code> table reference
     */
    public ResQuarter(String alias) {
        this(DSL.name(alias), RES_QUARTER);
    }

    /**
     * Create an aliased <code>res_quarter</code> table reference
     */
    public ResQuarter(Name alias) {
        this(alias, RES_QUARTER);
    }

    /**
     * Create a <code>res_quarter</code> table reference
     */
    public ResQuarter() {
        this(DSL.name("res_quarter"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ResQuarterRecord> getPrimaryKey() {
        return Keys.KEY_RES_QUARTER_PRIMARY;
    }

    @Override
    public ResQuarter as(String alias) {
        return new ResQuarter(DSL.name(alias), this);
    }

    @Override
    public ResQuarter as(Name alias) {
        return new ResQuarter(alias, this);
    }

    @Override
    public ResQuarter as(Table<?> alias) {
        return new ResQuarter(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResQuarter rename(String name) {
        return new ResQuarter(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResQuarter rename(Name name) {
        return new ResQuarter(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResQuarter rename(Table<?> name) {
        return new ResQuarter(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResQuarter where(Condition condition) {
        return new ResQuarter(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResQuarter where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResQuarter where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResQuarter where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResQuarter where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResQuarter where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResQuarter where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResQuarter where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResQuarter whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResQuarter whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
