/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables;


import com.example.demo.resources.repository.jooq.DefaultSchema;
import com.example.demo.resources.repository.jooq.Keys;
import com.example.demo.resources.repository.jooq.tables.records.ResSemesterRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 学期表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResSemester extends TableImpl<ResSemesterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>res_semester</code>
     */
    public static final ResSemester RES_SEMESTER = new ResSemester();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResSemesterRecord> getRecordType() {
        return ResSemesterRecord.class;
    }

    /**
     * The column <code>res_semester.id</code>.
     */
    public final TableField<ResSemesterRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>res_semester.start_year</code>. 学期起始年份（如 2023 表示该学期从
     * 2023 年开始）
     */
    public final TableField<ResSemesterRecord, Integer> START_YEAR = createField(DSL.name("start_year"), SQLDataType.INTEGER.nullable(false), this, "学期起始年份（如 2023 表示该学期从 2023 年开始）");

    /**
     * The column <code>res_semester.end_year</code>. 学期结束年份（如 2024 表示该学期至 2024
     * 年结束，用于跨年度学期场景）
     */
    public final TableField<ResSemesterRecord, Integer> END_YEAR = createField(DSL.name("end_year"), SQLDataType.INTEGER.nullable(false), this, "学期结束年份（如 2024 表示该学期至 2024 年结束，用于跨年度学期场景）");

    /**
     * The column <code>res_semester.quarter_code</code>. 学季标识（1-4 分别代表春 / 夏 / 秋
     * / 冬，或按学校实际划分，如 1 = 秋季、2 = 春季）
     */
    public final TableField<ResSemesterRecord, String> QUARTER_CODE = createField(DSL.name("quarter_code"), SQLDataType.VARCHAR(10).nullable(false), this, "学季标识（1-4 分别代表春 / 夏 / 秋 / 冬，或按学校实际划分，如 1 = 秋季、2 = 春季）");

    /**
     * The column <code>res_semester.semester_name</code>. 学期中文名称（如 “2023-2024
     * 学年第一学期”“2024 年夏季学期”）
     */
    public final TableField<ResSemesterRecord, String> SEMESTER_NAME = createField(DSL.name("semester_name"), SQLDataType.VARCHAR(50).nullable(false), this, "学期中文名称（如 “2023-2024 学年第一学期”“2024 年夏季学期”）");

    /**
     * The column <code>res_semester.english_name</code>. 学期英文名称（如 “2023-2024
     * Academic Year, First Semester”）
     */
    public final TableField<ResSemesterRecord, String> ENGLISH_NAME = createField(DSL.name("english_name"), SQLDataType.VARCHAR(100).nullable(false), this, "学期英文名称（如 “2023-2024 Academic Year, First Semester”）");

    /**
     * The column <code>res_semester.start_date</code>. 学期开始日期（精确到日，补充时间维度，如
     * 2023-09-01）
     */
    public final TableField<ResSemesterRecord, LocalDate> START_DATE = createField(DSL.name("start_date"), SQLDataType.LOCALDATE.nullable(false), this, "学期开始日期（精确到日，补充时间维度，如 2023-09-01）");

    /**
     * The column <code>res_semester.end_date</code>. 学期结束日期（精确到日，如 2024-01-15）
     */
    public final TableField<ResSemesterRecord, LocalDate> END_DATE = createField(DSL.name("end_date"), SQLDataType.LOCALDATE.nullable(false), this, "学期结束日期（精确到日，如 2024-01-15）");

    /**
     * The column <code>res_semester.is_current</code>. 是否当前学期（1 = 是，0 =
     * 否，用于快速查询当前活跃学期）
     */
    public final TableField<ResSemesterRecord, Byte> IS_CURRENT = createField(DSL.name("is_current"), SQLDataType.TINYINT.nullable(false), this, "是否当前学期（1 = 是，0 = 否，用于快速查询当前活跃学期）");

    /**
     * The column <code>res_semester.status</code>. 学期状态（0 = 未开始，1 = 进行中，2 =
     * 已结束，便于业务逻辑判断）
     */
    public final TableField<ResSemesterRecord, Byte> STATUS = createField(DSL.name("status"), SQLDataType.TINYINT.nullable(false), this, "学期状态（0 = 未开始，1 = 进行中，2 = 已结束，便于业务逻辑判断）");

    /**
     * The column <code>res_semester.create_by</code>. 创建人
     */
    public final TableField<ResSemesterRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "创建人");

    /**
     * The column <code>res_semester.create_time</code>. 创建时间
     */
    public final TableField<ResSemesterRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>res_semester.update_by</code>. 更新人
     */
    public final TableField<ResSemesterRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "更新人");

    /**
     * The column <code>res_semester.update_time</code>. 更新时间
     */
    public final TableField<ResSemesterRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>res_semester.chinese_name</code>.
     */
    public final TableField<ResSemesterRecord, String> CHINESE_NAME = createField(DSL.name("chinese_name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private ResSemester(Name alias, Table<ResSemesterRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ResSemester(Name alias, Table<ResSemesterRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("学期表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>res_semester</code> table reference
     */
    public ResSemester(String alias) {
        this(DSL.name(alias), RES_SEMESTER);
    }

    /**
     * Create an aliased <code>res_semester</code> table reference
     */
    public ResSemester(Name alias) {
        this(alias, RES_SEMESTER);
    }

    /**
     * Create a <code>res_semester</code> table reference
     */
    public ResSemester() {
        this(DSL.name("res_semester"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ResSemesterRecord> getPrimaryKey() {
        return Keys.KEY_RES_SEMESTER_PRIMARY;
    }

    @Override
    public ResSemester as(String alias) {
        return new ResSemester(DSL.name(alias), this);
    }

    @Override
    public ResSemester as(Name alias) {
        return new ResSemester(alias, this);
    }

    @Override
    public ResSemester as(Table<?> alias) {
        return new ResSemester(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResSemester rename(String name) {
        return new ResSemester(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResSemester rename(Name name) {
        return new ResSemester(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResSemester rename(Table<?> name) {
        return new ResSemester(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSemester where(Condition condition) {
        return new ResSemester(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSemester where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSemester where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSemester where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResSemester where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResSemester where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResSemester where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResSemester where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSemester whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSemester whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
