/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables;


import com.example.demo.resources.repository.jooq.DefaultSchema;
import com.example.demo.resources.repository.jooq.Keys;
import com.example.demo.resources.repository.jooq.tables.records.ResSchoolRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 学校表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResSchool extends TableImpl<ResSchoolRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>res_school</code>
     */
    public static final ResSchool RES_SCHOOL = new ResSchool();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResSchoolRecord> getRecordType() {
        return ResSchoolRecord.class;
    }

    /**
     * The column <code>res_school.id</code>. 主键
     */
    public final TableField<ResSchoolRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "主键");

    /**
     * The column <code>res_school.school_code</code>. 学校代码
     */
    public final TableField<ResSchoolRecord, String> SCHOOL_CODE = createField(DSL.name("school_code"), SQLDataType.VARCHAR(20).nullable(false), this, "学校代码");

    /**
     * The column <code>res_school.school_name</code>. 中文名称
     */
    public final TableField<ResSchoolRecord, String> SCHOOL_NAME = createField(DSL.name("school_name"), SQLDataType.VARCHAR(100).nullable(false), this, "中文名称");

    /**
     * The column <code>res_school.school_abbr</code>. 中文简称
     */
    public final TableField<ResSchoolRecord, String> SCHOOL_ABBR = createField(DSL.name("school_abbr"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "中文简称");

    /**
     * The column <code>res_school.english_name</code>. 英文名称
     */
    public final TableField<ResSchoolRecord, String> ENGLISH_NAME = createField(DSL.name("english_name"), SQLDataType.VARCHAR(200).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "英文名称");

    /**
     * The column <code>res_school.english_abbr</code>. 英文简称
     */
    public final TableField<ResSchoolRecord, String> ENGLISH_ABBR = createField(DSL.name("english_abbr"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "英文简称");

    /**
     * The column <code>res_school.key_school</code>. 重点学校
     */
    public final TableField<ResSchoolRecord, String> KEY_SCHOOL = createField(DSL.name("key_school"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "重点学校");

    /**
     * The column <code>res_school.org_structure</code>. 组织机构
     */
    public final TableField<ResSchoolRecord, String> ORG_STRUCTURE = createField(DSL.name("org_structure"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "组织机构");

    /**
     * The column <code>res_school.project_211</code>. 211 工程学校
     */
    public final TableField<ResSchoolRecord, String> PROJECT_211 = createField(DSL.name("project_211"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "211 工程学校");

    /**
     * The column <code>res_school.province</code>. 所属省
     */
    public final TableField<ResSchoolRecord, String> PROVINCE = createField(DSL.name("province"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "所属省");

    /**
     * The column <code>res_school.city</code>. 所属市
     */
    public final TableField<ResSchoolRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "所属市");

    /**
     * The column <code>res_school.online_dept</code>. 网络院系
     */
    public final TableField<ResSchoolRecord, String> ONLINE_DEPT = createField(DSL.name("online_dept"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "网络院系");

    /**
     * The column <code>res_school.anniversary_date</code>. 校庆日
     */
    public final TableField<ResSchoolRecord, LocalDate> ANNIVERSARY_DATE = createField(DSL.name("anniversary_date"), SQLDataType.LOCALDATE.defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATE)), this, "校庆日");

    /**
     * The column <code>res_school.competent_dept</code>. 主管部门
     */
    public final TableField<ResSchoolRecord, String> COMPETENT_DEPT = createField(DSL.name("competent_dept"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "主管部门");

    /**
     * The column <code>res_school.graduate_school</code>. 研究生院
     */
    public final TableField<ResSchoolRecord, String> GRADUATE_SCHOOL = createField(DSL.name("graduate_school"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "研究生院");

    /**
     * The column <code>res_school.school_type</code>. 办学类型
     */
    public final TableField<ResSchoolRecord, String> SCHOOL_TYPE = createField(DSL.name("school_type"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "办学类型");

    /**
     * The column <code>res_school.school_nature</code>. 学校性质
     */
    public final TableField<ResSchoolRecord, String> SCHOOL_NATURE = createField(DSL.name("school_nature"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "学校性质");

    /**
     * The column <code>res_school.adult_edu_dept</code>. 成教院系
     */
    public final TableField<ResSchoolRecord, String> ADULT_EDU_DEPT = createField(DSL.name("adult_edu_dept"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "成教院系");

    /**
     * The column <code>res_school.party_secretary</code>. 党委负责人
     */
    public final TableField<ResSchoolRecord, String> PARTY_SECRETARY = createField(DSL.name("party_secretary"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "党委负责人");

    /**
     * The column <code>res_school.discipline_count</code>. 学科门类数
     */
    public final TableField<ResSchoolRecord, Integer> DISCIPLINE_COUNT = createField(DSL.name("discipline_count"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "学科门类数");

    /**
     * The column <code>res_school.legal_representative</code>. 法定代表人
     */
    public final TableField<ResSchoolRecord, String> LEGAL_REPRESENTATIVE = createField(DSL.name("legal_representative"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "法定代表人");

    /**
     * The column <code>res_school.legal_cert_no</code>. 法人证书号
     */
    public final TableField<ResSchoolRecord, String> LEGAL_CERT_NO = createField(DSL.name("legal_cert_no"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "法人证书号");

    /**
     * The column <code>res_school.sponsor</code>. 学校举办者
     */
    public final TableField<ResSchoolRecord, String> SPONSOR = createField(DSL.name("sponsor"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "学校举办者");

    /**
     * The column <code>res_school.principal</code>. 校长
     */
    public final TableField<ResSchoolRecord, String> PRINCIPAL = createField(DSL.name("principal"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "校长");

    /**
     * The column <code>res_school.establish_date</code>. 建立年月
     */
    public final TableField<ResSchoolRecord, LocalDate> ESTABLISH_DATE = createField(DSL.name("establish_date"), SQLDataType.LOCALDATE.defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATE)), this, "建立年月");

    /**
     * The column <code>res_school.homepage_url</code>. 主页地址
     */
    public final TableField<ResSchoolRecord, String> HOMEPAGE_URL = createField(DSL.name("homepage_url"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "主页地址");

    /**
     * The column <code>res_school.fax</code>. 传真电话
     */
    public final TableField<ResSchoolRecord, String> FAX = createField(DSL.name("fax"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "传真电话");

    /**
     * The column <code>res_school.postal_code</code>. 邮政编码
     */
    public final TableField<ResSchoolRecord, String> POSTAL_CODE = createField(DSL.name("postal_code"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "邮政编码");

    /**
     * The column <code>res_school.contact_phone</code>. 联系电话
     */
    public final TableField<ResSchoolRecord, String> CONTACT_PHONE = createField(DSL.name("contact_phone"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "联系电话");

    /**
     * The column <code>res_school.email</code>. 电子邮箱
     */
    public final TableField<ResSchoolRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "电子邮箱");

    /**
     * The column <code>res_school.address</code>. 地址
     */
    public final TableField<ResSchoolRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(500).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "地址");

    /**
     * The column <code>res_school.intro</code>. 简介
     */
    public final TableField<ResSchoolRecord, String> INTRO = createField(DSL.name("intro"), SQLDataType.VARCHAR(1000).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "简介");

    /**
     * The column <code>res_school.create_by</code>. 创建人
     */
    public final TableField<ResSchoolRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "创建人");

    /**
     * The column <code>res_school.create_time</code>. 创建时间
     */
    public final TableField<ResSchoolRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>res_school.update_by</code>. 更新人
     */
    public final TableField<ResSchoolRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "更新人");

    /**
     * The column <code>res_school.update_time</code>. 更新时间
     */
    public final TableField<ResSchoolRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "更新时间");

    private ResSchool(Name alias, Table<ResSchoolRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ResSchool(Name alias, Table<ResSchoolRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("学校表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>res_school</code> table reference
     */
    public ResSchool(String alias) {
        this(DSL.name(alias), RES_SCHOOL);
    }

    /**
     * Create an aliased <code>res_school</code> table reference
     */
    public ResSchool(Name alias) {
        this(alias, RES_SCHOOL);
    }

    /**
     * Create a <code>res_school</code> table reference
     */
    public ResSchool() {
        this(DSL.name("res_school"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ResSchoolRecord> getPrimaryKey() {
        return Keys.KEY_RES_SCHOOL_PRIMARY;
    }

    @Override
    public ResSchool as(String alias) {
        return new ResSchool(DSL.name(alias), this);
    }

    @Override
    public ResSchool as(Name alias) {
        return new ResSchool(alias, this);
    }

    @Override
    public ResSchool as(Table<?> alias) {
        return new ResSchool(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResSchool rename(String name) {
        return new ResSchool(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResSchool rename(Name name) {
        return new ResSchool(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResSchool rename(Table<?> name) {
        return new ResSchool(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSchool where(Condition condition) {
        return new ResSchool(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSchool where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSchool where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSchool where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResSchool where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResSchool where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResSchool where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResSchool where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSchool whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResSchool whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
