/*
 * This file is generated by jOOQ.
 */
package com.example.ai.system.repository.jooq.tables;


import com.example.ai.system.repository.jooq.DefaultSchema;
import com.example.ai.system.repository.jooq.Keys;
import com.example.ai.system.repository.jooq.tables.records.SysUserRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SysUser extends TableImpl<SysUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sys_user</code>
     */
    public static final SysUser SYS_USER = new SysUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysUserRecord> getRecordType() {
        return SysUserRecord.class;
    }

    /**
     * The column <code>sys_user.id</code>.
     */
    public final TableField<SysUserRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>sys_user.account</code>. 账号
     */
    public final TableField<SysUserRecord, String> ACCOUNT = createField(DSL.name("account"), SQLDataType.VARCHAR(50).nullable(false), this, "账号");

    /**
     * The column <code>sys_user.username</code>. 名称
     */
    public final TableField<SysUserRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(100).nullable(false), this, "名称");

    /**
     * The column <code>sys_user.password</code>. 密码
     */
    public final TableField<SysUserRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(200).nullable(false), this, "密码");

    /**
     * The column <code>sys_user.email</code>. 邮箱
     */
    public final TableField<SysUserRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "邮箱");

    /**
     * The column <code>sys_user.gender_code</code>. 性别码
     */
    public final TableField<SysUserRecord, String> GENDER_CODE = createField(DSL.name("gender_code"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "性别码");

    /**
     * The column <code>sys_user.phone</code>. 手机号码
     */
    public final TableField<SysUserRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "手机号码");

    /**
     * The column <code>sys_user.user_status_code</code>. 状态码
     */
    public final TableField<SysUserRecord, String> USER_STATUS_CODE = createField(DSL.name("user_status_code"), SQLDataType.VARCHAR(20).nullable(false), this, "状态码");

    /**
     * The column <code>sys_user.create_by</code>. 创建人
     */
    public final TableField<SysUserRecord, String> CREATE_BY = createField(DSL.name("create_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "创建人");

    /**
     * The column <code>sys_user.create_time</code>. 创建时间
     */
    public final TableField<SysUserRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>sys_user.update_by</code>. 更新人
     */
    public final TableField<SysUserRecord, String> UPDATE_BY = createField(DSL.name("update_by"), SQLDataType.VARCHAR(64).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "更新人");

    /**
     * The column <code>sys_user.update_time</code>. 更新时间
     */
    public final TableField<SysUserRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "更新时间");

    private SysUser(Name alias, Table<SysUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SysUser(Name alias, Table<SysUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("用户表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sys_user</code> table reference
     */
    public SysUser(String alias) {
        this(DSL.name(alias), SYS_USER);
    }

    /**
     * Create an aliased <code>sys_user</code> table reference
     */
    public SysUser(Name alias) {
        this(alias, SYS_USER);
    }

    /**
     * Create a <code>sys_user</code> table reference
     */
    public SysUser() {
        this(DSL.name("sys_user"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<SysUserRecord> getPrimaryKey() {
        return Keys.KEY_SYS_USER_PRIMARY;
    }

    @Override
    public SysUser as(String alias) {
        return new SysUser(DSL.name(alias), this);
    }

    @Override
    public SysUser as(Name alias) {
        return new SysUser(alias, this);
    }

    @Override
    public SysUser as(Table<?> alias) {
        return new SysUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysUser rename(String name) {
        return new SysUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysUser rename(Name name) {
        return new SysUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysUser rename(Table<?> name) {
        return new SysUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysUser where(Condition condition) {
        return new SysUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
