/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq;


import com.example.demo.resources.repository.jooq.tables.ResCampus;
import com.example.demo.resources.repository.jooq.tables.ResCollege;
import com.example.demo.resources.repository.jooq.tables.ResCourse;
import com.example.demo.resources.repository.jooq.tables.ResDepartment;
import com.example.demo.resources.repository.jooq.tables.ResMajor;
import com.example.demo.resources.repository.jooq.tables.ResQuarter;
import com.example.demo.resources.repository.jooq.tables.ResSchool;
import com.example.demo.resources.repository.jooq.tables.ResSemester;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * 校区表
     */
    public final ResCampus RES_CAMPUS = ResCampus.RES_CAMPUS;

    /**
     * 学院表
     */
    public final ResCollege RES_COLLEGE = ResCollege.RES_COLLEGE;

    /**
     * 课程表
     */
    public final ResCourse RES_COURSE = ResCourse.RES_COURSE;

    /**
     * 部门表
     */
    public final ResDepartment RES_DEPARTMENT = ResDepartment.RES_DEPARTMENT;

    /**
     * 专业表
     */
    public final ResMajor RES_MAJOR = ResMajor.RES_MAJOR;

    /**
     * 学季字典表
     */
    public final ResQuarter RES_QUARTER = ResQuarter.RES_QUARTER;

    /**
     * 学校表
     */
    public final ResSchool RES_SCHOOL = ResSchool.RES_SCHOOL;

    /**
     * 学期表
     */
    public final ResSemester RES_SEMESTER = ResSemester.RES_SEMESTER;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super(DSL.name(""), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ResCampus.RES_CAMPUS,
            ResCollege.RES_COLLEGE,
            ResCourse.RES_COURSE,
            ResDepartment.RES_DEPARTMENT,
            ResMajor.RES_MAJOR,
            ResQuarter.RES_QUARTER,
            ResSchool.RES_SCHOOL,
            ResSemester.RES_SEMESTER
        );
    }
}
