/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq;


import com.example.demo.resources.repository.jooq.tables.ResCourse;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index RES_COURSE_IDX_SEMESTER_DEPARTMENT = Internal.createIndex(DSL.name("idx_semester_department"), ResCourse.RES_COURSE, new OrderField[] { ResCourse.RES_COURSE.DEPARTMENT_ID }, false);
    public static final Index RES_COURSE_IDX_TEACHER_ID = Internal.createIndex(DSL.name("idx_teacher_id"), ResCourse.RES_COURSE, new OrderField[] { ResCourse.RES_COURSE.TEACHER_ID }, false);
}
