/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq;


import com.example.demo.resources.repository.jooq.tables.ResSchool;
import com.example.demo.resources.repository.jooq.tables.records.ResSchoolRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ResSchoolRecord> KEY_RES_SCHOOL_PRIMARY = Internal.createUniqueKey(ResSchool.RES_SCHOOL, DSL.name("KEY_res_school_PRIMARY"), new TableField[] { ResSchool.RES_SCHOOL.ID }, true);
}
