/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq;


import com.example.demo.resources.repository.jooq.tables.ResCampus;
import com.example.demo.resources.repository.jooq.tables.ResCollege;
import com.example.demo.resources.repository.jooq.tables.ResCourse;
import com.example.demo.resources.repository.jooq.tables.ResDepartment;
import com.example.demo.resources.repository.jooq.tables.ResMajor;
import com.example.demo.resources.repository.jooq.tables.ResQuarter;
import com.example.demo.resources.repository.jooq.tables.ResSchool;
import com.example.demo.resources.repository.jooq.tables.ResSemester;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 校区表
     */
    public static final ResCampus RES_CAMPUS = ResCampus.RES_CAMPUS;

    /**
     * 学院表
     */
    public static final ResCollege RES_COLLEGE = ResCollege.RES_COLLEGE;

    /**
     * 课程表
     */
    public static final ResCourse RES_COURSE = ResCourse.RES_COURSE;

    /**
     * 部门表
     */
    public static final ResDepartment RES_DEPARTMENT = ResDepartment.RES_DEPARTMENT;

    /**
     * 专业表
     */
    public static final ResMajor RES_MAJOR = ResMajor.RES_MAJOR;

    /**
     * 学季字典表
     */
    public static final ResQuarter RES_QUARTER = ResQuarter.RES_QUARTER;

    /**
     * 学校表
     */
    public static final ResSchool RES_SCHOOL = ResSchool.RES_SCHOOL;

    /**
     * 学期表
     */
    public static final ResSemester RES_SEMESTER = ResSemester.RES_SEMESTER;
}
