/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq;


import com.example.demo.resources.repository.jooq.tables.ResSchool;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 学校表
     */
    public static final ResSchool RES_SCHOOL = ResSchool.RES_SCHOOL;
}
