/*
 * This file is generated by jOOQ.
 */
package com.example.ai.system.repository.jooq;


import com.example.ai.system.repository.jooq.tables.SysRole;
import com.example.ai.system.repository.jooq.tables.SysUser;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * 角色表
     */
    public final SysRole SYS_ROLE = SysRole.SYS_ROLE;

    /**
     * 用户表
     */
    public final SysUser SYS_USER = SysUser.SYS_USER;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super(DSL.name(""), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            SysRole.SYS_ROLE,
            SysUser.SYS_USER
        );
    }
}
