/*
 * This file is generated by jOOQ.
 */
package com.example.ai.system.repository.jooq;


import com.example.ai.system.repository.jooq.tables.SysPermission;
import com.example.ai.system.repository.jooq.tables.SysRole;
import com.example.ai.system.repository.jooq.tables.SysUser;
import com.example.ai.system.repository.jooq.tables.SysUserRole;
import com.example.ai.system.repository.jooq.tables.records.SysPermissionRecord;
import com.example.ai.system.repository.jooq.tables.records.SysRoleRecord;
import com.example.ai.system.repository.jooq.tables.records.SysUserRecord;
import com.example.ai.system.repository.jooq.tables.records.SysUserRoleRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SysPermissionRecord> KEY_SYS_PERMISSION_PRIMARY = Internal.createUniqueKey(SysPermission.SYS_PERMISSION, DSL.name("KEY_sys_permission_PRIMARY"), new TableField[] { SysPermission.SYS_PERMISSION.ID }, true);
    public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = Internal.createUniqueKey(SysRole.SYS_ROLE, DSL.name("KEY_sys_role_PRIMARY"), new TableField[] { SysRole.SYS_ROLE.ID }, true);
    public static final UniqueKey<SysUserRecord> KEY_SYS_USER_PRIMARY = Internal.createUniqueKey(SysUser.SYS_USER, DSL.name("KEY_sys_user_PRIMARY"), new TableField[] { SysUser.SYS_USER.ID }, true);
    public static final UniqueKey<SysUserRoleRecord> KEY_SYS_USER_ROLE_PRIMARY = Internal.createUniqueKey(SysUserRole.SYS_USER_ROLE, DSL.name("KEY_sys_user_role_PRIMARY"), new TableField[] { SysUserRole.SYS_USER_ROLE.ID }, true);
}
