/*
 * This file is generated by jOOQ.
 */
package com.example.ai.system.repository.jooq;


import com.example.ai.system.repository.jooq.tables.SysRole;
import com.example.ai.system.repository.jooq.tables.SysUser;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 角色表
     */
    public static final SysRole SYS_ROLE = SysRole.SYS_ROLE;

    /**
     * 用户表
     */
    public static final SysUser SYS_USER = SysUser.SYS_USER;
}
