/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables.records;


import com.example.demo.resources.repository.jooq.tables.ResCollege;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 学院表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResCollegeRecord extends UpdatableRecordImpl<ResCollegeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>res_college.id</code>. 学院 ID（主键）
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>res_college.id</code>. 学院 ID（主键）
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>res_college.college_code</code>.
     */
    public void setCollegeCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>res_college.college_code</code>.
     */
    public String getCollegeCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>res_college.campus_id</code>.
     */
    public void setCampusId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>res_college.campus_id</code>.
     */
    public String getCampusId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>res_college.college_name</code>.
     */
    public void setCollegeName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>res_college.college_name</code>.
     */
    public String getCollegeName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>res_college.college_abbr</code>.
     */
    public void setCollegeAbbr(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>res_college.college_abbr</code>.
     */
    public String getCollegeAbbr() {
        return (String) get(4);
    }

    /**
     * Setter for <code>res_college.english_name</code>.
     */
    public void setEnglishName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>res_college.english_name</code>.
     */
    public String getEnglishName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>res_college.dean</code>.
     */
    public void setDean(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>res_college.dean</code>.
     */
    public String getDean() {
        return (String) get(6);
    }

    /**
     * Setter for <code>res_college.landline</code>.
     */
    public void setLandline(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>res_college.landline</code>.
     */
    public String getLandline() {
        return (String) get(7);
    }

    /**
     * Setter for <code>res_college.phone</code>.
     */
    public void setPhone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>res_college.phone</code>.
     */
    public String getPhone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>res_college.email</code>.
     */
    public void setEmail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>res_college.email</code>.
     */
    public String getEmail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>res_college.intro</code>.
     */
    public void setIntro(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>res_college.intro</code>.
     */
    public String getIntro() {
        return (String) get(10);
    }

    /**
     * Setter for <code>res_college.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>res_college.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>res_college.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>res_college.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>res_college.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>res_college.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>res_college.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>res_college.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>res_college.campus_name</code>.
     */
    public void setCampusName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>res_college.campus_name</code>.
     */
    public String getCampusName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>res_college.chinese_abbr</code>.
     */
    public void setChineseAbbr(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>res_college.chinese_abbr</code>.
     */
    public String getChineseAbbr() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResCollegeRecord
     */
    public ResCollegeRecord() {
        super(ResCollege.RES_COLLEGE);
    }

    /**
     * Create a detached, initialised ResCollegeRecord
     */
    public ResCollegeRecord(String id, String collegeCode, String campusId, String collegeName, String collegeAbbr, String englishName, String dean, String landline, String phone, String email, String intro, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime, String campusName, String chineseAbbr) {
        super(ResCollege.RES_COLLEGE);

        setId(id);
        setCollegeCode(collegeCode);
        setCampusId(campusId);
        setCollegeName(collegeName);
        setCollegeAbbr(collegeAbbr);
        setEnglishName(englishName);
        setDean(dean);
        setLandline(landline);
        setPhone(phone);
        setEmail(email);
        setIntro(intro);
        setCreateBy(createBy);
        setCreateTime(createTime);
        setUpdateBy(updateBy);
        setUpdateTime(updateTime);
        setCampusName(campusName);
        setChineseAbbr(chineseAbbr);
        resetTouchedOnNotNull();
    }
}
