/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables.records;


import com.example.demo.resources.repository.jooq.tables.ResCourse;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 课程表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResCourseRecord extends UpdatableRecordImpl<ResCourseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>res_course.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>res_course.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>res_course.course_code</code>.
     */
    public void setCourseCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>res_course.course_code</code>.
     */
    public String getCourseCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>res_course.course_name</code>.
     */
    public void setCourseName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>res_course.course_name</code>.
     */
    public String getCourseName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>res_course.english_name</code>.
     */
    public void setEnglishName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>res_course.english_name</code>.
     */
    public String getEnglishName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>res_course.department_id</code>.
     */
    public void setDepartmentId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>res_course.department_id</code>.
     */
    public String getDepartmentId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>res_course.major_id</code>.
     */
    public void setMajorId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>res_course.major_id</code>.
     */
    public String getMajorId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>res_course.teacher_id</code>.
     */
    public void setTeacherId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>res_course.teacher_id</code>.
     */
    public String getTeacherId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>res_course.credit</code>.
     */
    public void setCredit(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>res_course.credit</code>.
     */
    public Double getCredit() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>res_course.total_hours</code>. 总学时（理论+实践）
     */
    public void setTotalHours(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>res_course.total_hours</code>. 总学时（理论+实践）
     */
    public Integer getTotalHours() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>res_course.theory_hours</code>. 理论学时
     */
    public void setTheoryHours(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>res_course.theory_hours</code>. 理论学时
     */
    public Integer getTheoryHours() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>res_course.practice_hours</code>. 实践学时
     */
    public void setPracticeHours(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>res_course.practice_hours</code>. 实践学时
     */
    public Integer getPracticeHours() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>res_course.course_type_code</code>.
     */
    public void setCourseTypeCode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>res_course.course_type_code</code>.
     */
    public String getCourseTypeCode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>res_course.teaching_mode_code</code>.
     */
    public void setTeachingModeCode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>res_course.teaching_mode_code</code>.
     */
    public String getTeachingModeCode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>res_course.assessment_type_code</code>.
     */
    public void setAssessmentTypeCode(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>res_course.assessment_type_code</code>.
     */
    public String getAssessmentTypeCode() {
        return (String) get(13);
    }

    /**
     * Setter for <code>res_course.description</code>.
     */
    public void setDescription(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>res_course.description</code>.
     */
    public String getDescription() {
        return (String) get(14);
    }

    /**
     * Setter for <code>res_course.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>res_course.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(15);
    }

    /**
     * Setter for <code>res_course.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>res_course.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>res_course.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>res_course.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(17);
    }

    /**
     * Setter for <code>res_course.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>res_course.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>res_course.chinese_name</code>.
     */
    public void setChineseName(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>res_course.chinese_name</code>.
     */
    public String getChineseName() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResCourseRecord
     */
    public ResCourseRecord() {
        super(ResCourse.RES_COURSE);
    }

    /**
     * Create a detached, initialised ResCourseRecord
     */
    public ResCourseRecord(String id, String courseCode, String courseName, String englishName, String departmentId, String majorId, String teacherId, Double credit, Integer totalHours, Integer theoryHours, Integer practiceHours, String courseTypeCode, String teachingModeCode, String assessmentTypeCode, String description, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime, String chineseName) {
        super(ResCourse.RES_COURSE);

        setId(id);
        setCourseCode(courseCode);
        setCourseName(courseName);
        setEnglishName(englishName);
        setDepartmentId(departmentId);
        setMajorId(majorId);
        setTeacherId(teacherId);
        setCredit(credit);
        setTotalHours(totalHours);
        setTheoryHours(theoryHours);
        setPracticeHours(practiceHours);
        setCourseTypeCode(courseTypeCode);
        setTeachingModeCode(teachingModeCode);
        setAssessmentTypeCode(assessmentTypeCode);
        setDescription(description);
        setCreateBy(createBy);
        setCreateTime(createTime);
        setUpdateBy(updateBy);
        setUpdateTime(updateTime);
        setChineseName(chineseName);
        resetTouchedOnNotNull();
    }
}
