/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables.records;


import com.example.demo.resources.repository.jooq.tables.ResCampus;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 校区表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResCampusRecord extends UpdatableRecordImpl<ResCampusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>res_campus.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>res_campus.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>res_campus.campus_code</code>.
     */
    public void setCampusCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>res_campus.campus_code</code>.
     */
    public String getCampusCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>res_campus.school_id</code>.
     */
    public void setSchoolId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>res_campus.school_id</code>.
     */
    public String getSchoolId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>res_campus.campus_name</code>.
     */
    public void setCampusName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>res_campus.campus_name</code>.
     */
    public String getCampusName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>res_campus.english_name</code>.
     */
    public void setEnglishName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>res_campus.english_name</code>.
     */
    public String getEnglishName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>res_campus.address</code>.
     */
    public void setAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>res_campus.address</code>.
     */
    public String getAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>res_campus.principal</code>.
     */
    public void setPrincipal(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>res_campus.principal</code>.
     */
    public String getPrincipal() {
        return (String) get(6);
    }

    /**
     * Setter for <code>res_campus.landline</code>.
     */
    public void setLandline(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>res_campus.landline</code>.
     */
    public String getLandline() {
        return (String) get(7);
    }

    /**
     * Setter for <code>res_campus.phone</code>.
     */
    public void setPhone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>res_campus.phone</code>.
     */
    public String getPhone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>res_campus.email</code>.
     */
    public void setEmail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>res_campus.email</code>.
     */
    public String getEmail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>res_campus.intro</code>.
     */
    public void setIntro(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>res_campus.intro</code>.
     */
    public String getIntro() {
        return (String) get(10);
    }

    /**
     * Setter for <code>res_campus.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>res_campus.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>res_campus.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>res_campus.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>res_campus.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>res_campus.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>res_campus.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>res_campus.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResCampusRecord
     */
    public ResCampusRecord() {
        super(ResCampus.RES_CAMPUS);
    }

    /**
     * Create a detached, initialised ResCampusRecord
     */
    public ResCampusRecord(String id, String campusCode, String schoolId, String campusName, String englishName, String address, String principal, String landline, String phone, String email, String intro, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime) {
        super(ResCampus.RES_CAMPUS);

        setId(id);
        setCampusCode(campusCode);
        setSchoolId(schoolId);
        setCampusName(campusName);
        setEnglishName(englishName);
        setAddress(address);
        setPrincipal(principal);
        setLandline(landline);
        setPhone(phone);
        setEmail(email);
        setIntro(intro);
        setCreateBy(createBy);
        setCreateTime(createTime);
        setUpdateBy(updateBy);
        setUpdateTime(updateTime);
        resetTouchedOnNotNull();
    }
}
