/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables.records;


import com.example.demo.resources.repository.jooq.tables.ResDepartment;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 部门表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResDepartmentRecord extends UpdatableRecordImpl<ResDepartmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>res_department.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>res_department.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>res_department.college_id</code>. 学院 ID
     */
    public void setCollegeId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>res_department.college_id</code>. 学院 ID
     */
    public String getCollegeId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>res_department.department_code</code>. 部门编号
     */
    public void setDepartmentCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>res_department.department_code</code>. 部门编号
     */
    public String getDepartmentCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>res_department.department_name</code>. 部门名称
     */
    public void setDepartmentName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>res_department.department_name</code>. 部门名称
     */
    public String getDepartmentName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>res_department.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>res_department.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>res_department.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>res_department.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>res_department.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>res_department.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>res_department.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>res_department.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResDepartmentRecord
     */
    public ResDepartmentRecord() {
        super(ResDepartment.RES_DEPARTMENT);
    }

    /**
     * Create a detached, initialised ResDepartmentRecord
     */
    public ResDepartmentRecord(String id, String collegeId, String departmentCode, String departmentName, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime) {
        super(ResDepartment.RES_DEPARTMENT);

        setId(id);
        setCollegeId(collegeId);
        setDepartmentCode(departmentCode);
        setDepartmentName(departmentName);
        setCreateBy(createBy);
        setCreateTime(createTime);
        setUpdateBy(updateBy);
        setUpdateTime(updateTime);
        resetTouchedOnNotNull();
    }
}
