/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables.records;


import com.example.demo.resources.repository.jooq.tables.ResMajor;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 专业表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResMajorRecord extends UpdatableRecordImpl<ResMajorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>res_major.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>res_major.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>res_major.major_code</code>. 专业代码
     */
    public void setMajorCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>res_major.major_code</code>. 专业代码
     */
    public String getMajorCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>res_major.college_id</code>. 学院 ID
     */
    public void setCollegeId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>res_major.college_id</code>. 学院 ID
     */
    public String getCollegeId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>res_major.major_name</code>. 专业中文名称
     */
    public void setMajorName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>res_major.major_name</code>. 专业中文名称
     */
    public String getMajorName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>res_major.major_abbr</code>. 专业中文简称
     */
    public void setMajorAbbr(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>res_major.major_abbr</code>. 专业中文简称
     */
    public String getMajorAbbr() {
        return (String) get(4);
    }

    /**
     * Setter for <code>res_major.english_name</code>. 专业英文名称
     */
    public void setEnglishName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>res_major.english_name</code>. 专业英文名称
     */
    public String getEnglishName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>res_major.degree</code>. 授予学位
     */
    public void setDegree(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>res_major.degree</code>. 授予学位
     */
    public String getDegree() {
        return (String) get(6);
    }

    /**
     * Setter for <code>res_major.years</code>. 学制年限
     */
    public void setYears(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>res_major.years</code>. 学制年限
     */
    public Integer getYears() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>res_major.intro</code>. 简介
     */
    public void setIntro(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>res_major.intro</code>. 简介
     */
    public String getIntro() {
        return (String) get(8);
    }

    /**
     * Setter for <code>res_major.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>res_major.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>res_major.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>res_major.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>res_major.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>res_major.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>res_major.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>res_major.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>res_major.chinese_abbr</code>.
     */
    public void setChineseAbbr(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>res_major.chinese_abbr</code>.
     */
    public String getChineseAbbr() {
        return (String) get(13);
    }

    /**
     * Setter for <code>res_major.chinese_name</code>.
     */
    public void setChineseName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>res_major.chinese_name</code>.
     */
    public String getChineseName() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResMajorRecord
     */
    public ResMajorRecord() {
        super(ResMajor.RES_MAJOR);
    }

    /**
     * Create a detached, initialised ResMajorRecord
     */
    public ResMajorRecord(String id, String majorCode, String collegeId, String majorName, String majorAbbr, String englishName, String degree, Integer years, String intro, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime, String chineseAbbr, String chineseName) {
        super(ResMajor.RES_MAJOR);

        setId(id);
        setMajorCode(majorCode);
        setCollegeId(collegeId);
        setMajorName(majorName);
        setMajorAbbr(majorAbbr);
        setEnglishName(englishName);
        setDegree(degree);
        setYears(years);
        setIntro(intro);
        setCreateBy(createBy);
        setCreateTime(createTime);
        setUpdateBy(updateBy);
        setUpdateTime(updateTime);
        setChineseAbbr(chineseAbbr);
        setChineseName(chineseName);
        resetTouchedOnNotNull();
    }
}
