/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables.records;


import com.example.demo.resources.repository.jooq.tables.ResQuarter;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 学季字典表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResQuarterRecord extends UpdatableRecordImpl<ResQuarterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>res_quarter.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>res_quarter.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>res_quarter.quarter_code</code>. 代码
     */
    public void setQuarterCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>res_quarter.quarter_code</code>. 代码
     */
    public String getQuarterCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>res_quarter.quarter_name</code>. 名称
     */
    public void setQuarterName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>res_quarter.quarter_name</code>. 名称
     */
    public String getQuarterName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>res_quarter.english_name</code>. 英文名称
     */
    public void setEnglishName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>res_quarter.english_name</code>. 英文名称
     */
    public String getEnglishName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>res_quarter.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>res_quarter.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>res_quarter.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>res_quarter.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>res_quarter.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>res_quarter.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>res_quarter.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>res_quarter.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>res_quarter.chinese_name</code>.
     */
    public void setChineseName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>res_quarter.chinese_name</code>.
     */
    public String getChineseName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>res_quarter.code</code>.
     */
    public void setCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>res_quarter.code</code>.
     */
    public String getCode() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResQuarterRecord
     */
    public ResQuarterRecord() {
        super(ResQuarter.RES_QUARTER);
    }

    /**
     * Create a detached, initialised ResQuarterRecord
     */
    public ResQuarterRecord(String id, String quarterCode, String quarterName, String englishName, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime, String chineseName, String code) {
        super(ResQuarter.RES_QUARTER);

        setId(id);
        setQuarterCode(quarterCode);
        setQuarterName(quarterName);
        setEnglishName(englishName);
        setCreateBy(createBy);
        setCreateTime(createTime);
        setUpdateBy(updateBy);
        setUpdateTime(updateTime);
        setChineseName(chineseName);
        setCode(code);
        resetTouchedOnNotNull();
    }
}
