/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables.records;


import com.example.demo.resources.repository.jooq.tables.ResSchool;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 学校表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResSchoolRecord extends UpdatableRecordImpl<ResSchoolRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>res_school.id</code>. 主键
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>res_school.id</code>. 主键
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>res_school.school_code</code>. 学校代码
     */
    public void setSchoolCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>res_school.school_code</code>. 学校代码
     */
    public String getSchoolCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>res_school.school_name</code>. 中文名称
     */
    public void setSchoolName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>res_school.school_name</code>. 中文名称
     */
    public String getSchoolName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>res_school.school_abbr</code>. 中文简称
     */
    public void setSchoolAbbr(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>res_school.school_abbr</code>. 中文简称
     */
    public String getSchoolAbbr() {
        return (String) get(3);
    }

    /**
     * Setter for <code>res_school.english_name</code>. 英文名称
     */
    public void setEnglishName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>res_school.english_name</code>. 英文名称
     */
    public String getEnglishName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>res_school.english_abbr</code>. 英文简称
     */
    public void setEnglishAbbr(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>res_school.english_abbr</code>. 英文简称
     */
    public String getEnglishAbbr() {
        return (String) get(5);
    }

    /**
     * Setter for <code>res_school.key_school</code>. 重点学校
     */
    public void setKeySchool(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>res_school.key_school</code>. 重点学校
     */
    public String getKeySchool() {
        return (String) get(6);
    }

    /**
     * Setter for <code>res_school.org_structure</code>. 组织机构
     */
    public void setOrgStructure(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>res_school.org_structure</code>. 组织机构
     */
    public String getOrgStructure() {
        return (String) get(7);
    }

    /**
     * Setter for <code>res_school.project_211</code>. 211 工程学校
     */
    public void setProject_211(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>res_school.project_211</code>. 211 工程学校
     */
    public String getProject_211() {
        return (String) get(8);
    }

    /**
     * Setter for <code>res_school.province</code>. 所属省
     */
    public void setProvince(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>res_school.province</code>. 所属省
     */
    public String getProvince() {
        return (String) get(9);
    }

    /**
     * Setter for <code>res_school.city</code>. 所属市
     */
    public void setCity(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>res_school.city</code>. 所属市
     */
    public String getCity() {
        return (String) get(10);
    }

    /**
     * Setter for <code>res_school.online_dept</code>. 网络院系
     */
    public void setOnlineDept(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>res_school.online_dept</code>. 网络院系
     */
    public String getOnlineDept() {
        return (String) get(11);
    }

    /**
     * Setter for <code>res_school.anniversary_date</code>. 校庆日
     */
    public void setAnniversaryDate(LocalDate value) {
        set(12, value);
    }

    /**
     * Getter for <code>res_school.anniversary_date</code>. 校庆日
     */
    public LocalDate getAnniversaryDate() {
        return (LocalDate) get(12);
    }

    /**
     * Setter for <code>res_school.competent_dept</code>. 主管部门
     */
    public void setCompetentDept(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>res_school.competent_dept</code>. 主管部门
     */
    public String getCompetentDept() {
        return (String) get(13);
    }

    /**
     * Setter for <code>res_school.graduate_school</code>. 研究生院
     */
    public void setGraduateSchool(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>res_school.graduate_school</code>. 研究生院
     */
    public String getGraduateSchool() {
        return (String) get(14);
    }

    /**
     * Setter for <code>res_school.school_type</code>. 办学类型
     */
    public void setSchoolType(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>res_school.school_type</code>. 办学类型
     */
    public String getSchoolType() {
        return (String) get(15);
    }

    /**
     * Setter for <code>res_school.school_nature</code>. 学校性质
     */
    public void setSchoolNature(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>res_school.school_nature</code>. 学校性质
     */
    public String getSchoolNature() {
        return (String) get(16);
    }

    /**
     * Setter for <code>res_school.adult_edu_dept</code>. 成教院系
     */
    public void setAdultEduDept(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>res_school.adult_edu_dept</code>. 成教院系
     */
    public String getAdultEduDept() {
        return (String) get(17);
    }

    /**
     * Setter for <code>res_school.party_secretary</code>. 党委负责人
     */
    public void setPartySecretary(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>res_school.party_secretary</code>. 党委负责人
     */
    public String getPartySecretary() {
        return (String) get(18);
    }

    /**
     * Setter for <code>res_school.discipline_count</code>. 学科门类数
     */
    public void setDisciplineCount(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>res_school.discipline_count</code>. 学科门类数
     */
    public Integer getDisciplineCount() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>res_school.legal_representative</code>. 法定代表人
     */
    public void setLegalRepresentative(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>res_school.legal_representative</code>. 法定代表人
     */
    public String getLegalRepresentative() {
        return (String) get(20);
    }

    /**
     * Setter for <code>res_school.legal_cert_no</code>. 法人证书号
     */
    public void setLegalCertNo(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>res_school.legal_cert_no</code>. 法人证书号
     */
    public String getLegalCertNo() {
        return (String) get(21);
    }

    /**
     * Setter for <code>res_school.sponsor</code>. 学校举办者
     */
    public void setSponsor(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>res_school.sponsor</code>. 学校举办者
     */
    public String getSponsor() {
        return (String) get(22);
    }

    /**
     * Setter for <code>res_school.principal</code>. 校长
     */
    public void setPrincipal(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>res_school.principal</code>. 校长
     */
    public String getPrincipal() {
        return (String) get(23);
    }

    /**
     * Setter for <code>res_school.establish_date</code>. 建立年月
     */
    public void setEstablishDate(LocalDate value) {
        set(24, value);
    }

    /**
     * Getter for <code>res_school.establish_date</code>. 建立年月
     */
    public LocalDate getEstablishDate() {
        return (LocalDate) get(24);
    }

    /**
     * Setter for <code>res_school.homepage_url</code>. 主页地址
     */
    public void setHomepageUrl(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>res_school.homepage_url</code>. 主页地址
     */
    public String getHomepageUrl() {
        return (String) get(25);
    }

    /**
     * Setter for <code>res_school.fax</code>. 传真电话
     */
    public void setFax(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>res_school.fax</code>. 传真电话
     */
    public String getFax() {
        return (String) get(26);
    }

    /**
     * Setter for <code>res_school.postal_code</code>. 邮政编码
     */
    public void setPostalCode(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>res_school.postal_code</code>. 邮政编码
     */
    public String getPostalCode() {
        return (String) get(27);
    }

    /**
     * Setter for <code>res_school.contact_phone</code>. 联系电话
     */
    public void setContactPhone(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>res_school.contact_phone</code>. 联系电话
     */
    public String getContactPhone() {
        return (String) get(28);
    }

    /**
     * Setter for <code>res_school.email</code>. 电子邮箱
     */
    public void setEmail(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>res_school.email</code>. 电子邮箱
     */
    public String getEmail() {
        return (String) get(29);
    }

    /**
     * Setter for <code>res_school.address</code>. 地址
     */
    public void setAddress(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>res_school.address</code>. 地址
     */
    public String getAddress() {
        return (String) get(30);
    }

    /**
     * Setter for <code>res_school.intro</code>. 简介
     */
    public void setIntro(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>res_school.intro</code>. 简介
     */
    public String getIntro() {
        return (String) get(31);
    }

    /**
     * Setter for <code>res_school.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>res_school.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(32);
    }

    /**
     * Setter for <code>res_school.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(33, value);
    }

    /**
     * Getter for <code>res_school.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(33);
    }

    /**
     * Setter for <code>res_school.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>res_school.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(34);
    }

    /**
     * Setter for <code>res_school.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(35, value);
    }

    /**
     * Getter for <code>res_school.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(35);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResSchoolRecord
     */
    public ResSchoolRecord() {
        super(ResSchool.RES_SCHOOL);
    }

    /**
     * Create a detached, initialised ResSchoolRecord
     */
    public ResSchoolRecord(String id, String schoolCode, String schoolName, String schoolAbbr, String englishName, String englishAbbr, String keySchool, String orgStructure, String project_211, String province, String city, String onlineDept, LocalDate anniversaryDate, String competentDept, String graduateSchool, String schoolType, String schoolNature, String adultEduDept, String partySecretary, Integer disciplineCount, String legalRepresentative, String legalCertNo, String sponsor, String principal, LocalDate establishDate, String homepageUrl, String fax, String postalCode, String contactPhone, String email, String address, String intro, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime) {
        super(ResSchool.RES_SCHOOL);

        setId(id);
        setSchoolCode(schoolCode);
        setSchoolName(schoolName);
        setSchoolAbbr(schoolAbbr);
        setEnglishName(englishName);
        setEnglishAbbr(englishAbbr);
        setKeySchool(keySchool);
        setOrgStructure(orgStructure);
        setProject_211(project_211);
        setProvince(province);
        setCity(city);
        setOnlineDept(onlineDept);
        setAnniversaryDate(anniversaryDate);
        setCompetentDept(competentDept);
        setGraduateSchool(graduateSchool);
        setSchoolType(schoolType);
        setSchoolNature(schoolNature);
        setAdultEduDept(adultEduDept);
        setPartySecretary(partySecretary);
        setDisciplineCount(disciplineCount);
        setLegalRepresentative(legalRepresentative);
        setLegalCertNo(legalCertNo);
        setSponsor(sponsor);
        setPrincipal(principal);
        setEstablishDate(establishDate);
        setHomepageUrl(homepageUrl);
        setFax(fax);
        setPostalCode(postalCode);
        setContactPhone(contactPhone);
        setEmail(email);
        setAddress(address);
        setIntro(intro);
        setCreateBy(createBy);
        setCreateTime(createTime);
        setUpdateBy(updateBy);
        setUpdateTime(updateTime);
        resetTouchedOnNotNull();
    }
}
