/*
 * This file is generated by jOOQ.
 */
package com.example.demo.resources.repository.jooq.tables.records;


import com.example.demo.resources.repository.jooq.tables.ResSemester;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 学期表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResSemesterRecord extends UpdatableRecordImpl<ResSemesterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>res_semester.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>res_semester.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>res_semester.start_year</code>. 学期起始年份（如 2023 表示该学期从
     * 2023 年开始）
     */
    public void setStartYear(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>res_semester.start_year</code>. 学期起始年份（如 2023 表示该学期从
     * 2023 年开始）
     */
    public Integer getStartYear() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>res_semester.end_year</code>. 学期结束年份（如 2024 表示该学期至 2024
     * 年结束，用于跨年度学期场景）
     */
    public void setEndYear(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>res_semester.end_year</code>. 学期结束年份（如 2024 表示该学期至 2024
     * 年结束，用于跨年度学期场景）
     */
    public Integer getEndYear() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>res_semester.quarter_code</code>. 学季标识（1-4 分别代表春 / 夏 / 秋
     * / 冬，或按学校实际划分，如 1 = 秋季、2 = 春季）
     */
    public void setQuarterCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>res_semester.quarter_code</code>. 学季标识（1-4 分别代表春 / 夏 / 秋
     * / 冬，或按学校实际划分，如 1 = 秋季、2 = 春季）
     */
    public String getQuarterCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>res_semester.semester_name</code>. 学期中文名称（如 “2023-2024
     * 学年第一学期”“2024 年夏季学期”）
     */
    public void setSemesterName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>res_semester.semester_name</code>. 学期中文名称（如 “2023-2024
     * 学年第一学期”“2024 年夏季学期”）
     */
    public String getSemesterName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>res_semester.english_name</code>. 学期英文名称（如 “2023-2024
     * Academic Year, First Semester”）
     */
    public void setEnglishName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>res_semester.english_name</code>. 学期英文名称（如 “2023-2024
     * Academic Year, First Semester”）
     */
    public String getEnglishName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>res_semester.start_date</code>. 学期开始日期（精确到日，补充时间维度，如
     * 2023-09-01）
     */
    public void setStartDate(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>res_semester.start_date</code>. 学期开始日期（精确到日，补充时间维度，如
     * 2023-09-01）
     */
    public LocalDate getStartDate() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>res_semester.end_date</code>. 学期结束日期（精确到日，如 2024-01-15）
     */
    public void setEndDate(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>res_semester.end_date</code>. 学期结束日期（精确到日，如 2024-01-15）
     */
    public LocalDate getEndDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>res_semester.is_current</code>. 是否当前学期（1 = 是，0 =
     * 否，用于快速查询当前活跃学期）
     */
    public void setIsCurrent(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>res_semester.is_current</code>. 是否当前学期（1 = 是，0 =
     * 否，用于快速查询当前活跃学期）
     */
    public Byte getIsCurrent() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>res_semester.status</code>. 学期状态（0 = 未开始，1 = 进行中，2 =
     * 已结束，便于业务逻辑判断）
     */
    public void setStatus(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>res_semester.status</code>. 学期状态（0 = 未开始，1 = 进行中，2 =
     * 已结束，便于业务逻辑判断）
     */
    public Byte getStatus() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>res_semester.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>res_semester.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>res_semester.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>res_semester.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>res_semester.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>res_semester.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>res_semester.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>res_semester.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>res_semester.chinese_name</code>.
     */
    public void setChineseName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>res_semester.chinese_name</code>.
     */
    public String getChineseName() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResSemesterRecord
     */
    public ResSemesterRecord() {
        super(ResSemester.RES_SEMESTER);
    }

    /**
     * Create a detached, initialised ResSemesterRecord
     */
    public ResSemesterRecord(String id, Integer startYear, Integer endYear, String quarterCode, String semesterName, String englishName, LocalDate startDate, LocalDate endDate, Byte isCurrent, Byte status, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime, String chineseName) {
        super(ResSemester.RES_SEMESTER);

        setId(id);
        setStartYear(startYear);
        setEndYear(endYear);
        setQuarterCode(quarterCode);
        setSemesterName(semesterName);
        setEnglishName(englishName);
        setStartDate(startDate);
        setEndDate(endDate);
        setIsCurrent(isCurrent);
        setStatus(status);
        setCreateBy(createBy);
        setCreateTime(createTime);
        setUpdateBy(updateBy);
        setUpdateTime(updateTime);
        setChineseName(chineseName);
        resetTouchedOnNotNull();
    }
}
