/*
 * This file is generated by jOOQ.
 */
package com.example.ai.system.repository.jooq.tables.records;


import com.example.ai.system.repository.jooq.tables.SysRole;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SysRoleRecord extends UpdatableRecordImpl<SysRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sys_role.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_role.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_role.role_code</code>.
     */
    public void setRoleCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_role.role_code</code>.
     */
    public String getRoleCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sys_role.role_name</code>. 角色名称
     */
    public void setRoleName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_role.role_name</code>. 角色名称
     */
    public String getRoleName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sys_role.description</code>. 角色描述
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_role.description</code>. 角色描述
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_role.enabled</code>. 是否启用
     */
    public void setEnabled(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_role.enabled</code>. 是否启用
     */
    public String getEnabled() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sys_role.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sys_role.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sys_role.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>sys_role.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>sys_role.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sys_role.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sys_role.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>sys_role.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRoleRecord
     */
    public SysRoleRecord() {
        super(SysRole.SYS_ROLE);
    }

    /**
     * Create a detached, initialised SysRoleRecord
     */
    public SysRoleRecord(String id, String roleCode, String roleName, String description, String enabled, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime) {
        super(SysRole.SYS_ROLE);

        setId(id);
        setRoleCode(roleCode);
        setRoleName(roleName);
        setDescription(description);
        setEnabled(enabled);
        setCreateBy(createBy);
        setCreateTime(createTime);
        setUpdateBy(updateBy);
        setUpdateTime(updateTime);
        resetTouchedOnNotNull();
    }
}
