/*
 * This file is generated by jOOQ.
 */
package com.example.ai.system.repository.jooq.tables.records;


import com.example.ai.system.repository.jooq.tables.SysUserRole;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SysUserRoleRecord extends UpdatableRecordImpl<SysUserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sys_user_role.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_user_role.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_user_role.user_id</code>. 用户 ID
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_user_role.user_id</code>. 用户 ID
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sys_user_role.role_id</code>. 角色 ID
     */
    public void setRoleId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_user_role.role_id</code>. 角色 ID
     */
    public String getRoleId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sys_user_role.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_user_role.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_user_role.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_user_role.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>sys_user_role.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sys_user_role.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sys_user_role.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>sys_user_role.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRoleRecord
     */
    public SysUserRoleRecord() {
        super(SysUserRole.SYS_USER_ROLE);
    }

    /**
     * Create a detached, initialised SysUserRoleRecord
     */
    public SysUserRoleRecord(String id, String userId, String roleId, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime) {
        super(SysUserRole.SYS_USER_ROLE);

        setId(id);
        setUserId(userId);
        setRoleId(roleId);
        setCreateBy(createBy);
        setCreateTime(createTime);
        setUpdateBy(updateBy);
        setUpdateTime(updateTime);
        resetTouchedOnNotNull();
    }
}
