/*
 * This file is generated by jOOQ.
 */
package com.example.ai.system.repository.jooq.tables.records;


import com.example.ai.system.repository.jooq.tables.SysUser;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SysUserRecord extends UpdatableRecordImpl<SysUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sys_user.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sys_user.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sys_user.account</code>. 账号
     */
    public void setAccount(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sys_user.account</code>. 账号
     */
    public String getAccount() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sys_user.username</code>. 名称
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sys_user.username</code>. 名称
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sys_user.password</code>. 密码
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sys_user.password</code>. 密码
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sys_user.email</code>. 邮箱
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sys_user.email</code>. 邮箱
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sys_user.gender_code</code>. 性别码
     */
    public void setGenderCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sys_user.gender_code</code>. 性别码
     */
    public String getGenderCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sys_user.phone</code>. 手机号码
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sys_user.phone</code>. 手机号码
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sys_user.user_status_code</code>. 状态码
     */
    public void setUserStatusCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sys_user.user_status_code</code>. 状态码
     */
    public String getUserStatusCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sys_user.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>sys_user.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>sys_user.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>sys_user.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>sys_user.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>sys_user.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>sys_user.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>sys_user.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRecord
     */
    public SysUserRecord() {
        super(SysUser.SYS_USER);
    }

    /**
     * Create a detached, initialised SysUserRecord
     */
    public SysUserRecord(String id, String account, String username, String password, String email, String genderCode, String phone, String userStatusCode, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime) {
        super(SysUser.SYS_USER);

        setId(id);
        setAccount(account);
        setUsername(username);
        setPassword(password);
        setEmail(email);
        setGenderCode(genderCode);
        setPhone(phone);
        setUserStatusCode(userStatusCode);
        setCreateBy(createBy);
        setCreateTime(createTime);
        setUpdateBy(updateBy);
        setUpdateTime(updateTime);
        resetTouchedOnNotNull();
    }
}
